### GET a specific book
GET http://localhost:3000/api/user
content-type: application/json

### GET
GET http://localhost:3000/api/applications
content-type: application/json

### GET
GET http://localhost:3000/api/contacts
content-type: application/json

### Register

POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name": "John Doe",
    "email": "example@example.com",
    "password": "test_test"
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "name": "John Doe",
    "email": "example@example.com",
    "password": "test_test"
}

### Login
# @name login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "hogehoge"
}

### ME
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{login.response.body.token}}

### Programs
GET http://localhost:3000/api/schools
Authorization: Bearer {{login.response.body.token}}

### Program by Id
GET http://localhost:3000/api/schools/uiuc-master-of-computer-science-mcs-mcs
Authorization: Bearer {{login.response.body.token}}

### Create Application
POST http://localhost:3000/api/application
content-type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "schoolName": "Carnegie Mellon University", 
    "programId": "carnegie-mellon-m-s-in-computer-science-ms", 
    "programName": "M.S. in Computer Science",
    "deadlines": []
}